### ISSUE TITLE
Literally anyone can delete entries?

### ISSUE THREAD

**Issue by BjoernPetersen** [OpenAlcoholics/card-review-website#5]

**Comment by torbencarstens** [comment]
Yes.
I'll probably just put up a .htaccess at some point.

**Comment by BjoernPetersen** [comment]
What kind of underengineering would that be? Maybe some kind of .htaccess-as-a-service exists?

**Comment by torbencarstens** [comment]
Should be somewhat simple to build the service, you'd just need to mount the http endpoint you're getting back via httpfs2 or similar.. 

That server would of course need auth as well so only you can modify your own entries..

**Comment by BjoernPetersen** [comment]
Dogfooding

**Comment by torbencarstens** [comment]
Until someone builds this service, we'll have to live with cloudflare access.

review.saufautom.at/add is public, everything else can be accessed by people in this (OpenAlcoholics) organization.
